services:
  - type: web
    name: flowise
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: FLOWISE_USERNAME
        sync: false
      - key: FLOWISE_PASSWORD
        sync: false
      - key: DATABASE_PATH
        value: /data/database.sqlite
      - key: APIKEY_PATH
        value: /data/apikeys.json
      - key: SECRETKEY_PATH
        value: /data/secrets.json
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
