services:
  - type: web
    name: flowise
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: FLOWISE_USERNAME
        sync: false
      - key: FLOWISE_PASSWORD
        sync: false
      - key: DATABASE_PATH
        value: ./database.sqlite
      - key: APIKEY_PATH
        value: ./apikeys.json
      - key: SECRETKEY_PATH
        value: ./secrets.json
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_UPLOAD_SIZE
        value: "10MB"
